#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh &

#$HOME/.config/polybar/launch.sh
#killall -b picom; picom &
#feh --bg-scale ~/voi/162536.png &

setxkbmap -option grp:alt_shift_toggle us,ru &

bspc monitor -d I II III IV

bspc config border_width 1
bspc config window_gap 0

bspc config split_ratio 0.5
#bspc config borderless_monocle true
#bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config click_to_focus none
#bspc config automatic_scheme alternate
#bspc config automatic_scheme
bspc config automatic_scheme longest_side
bspc config removal_adjustment on
#bspc config automatic_scheme spiral
bspc config pointer_modifier $Mod
#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner

bspc rule -a obs state=floating center=on
bspc rule -a Nsxiv state=floating center=on
bspc rule -a URxvt state=floating center=on
bspc rule -a mpv state=floating center=on rectangle=1050x730+0+0
bspc rule -a kitty state=floating center=on ectangle=600x500+0+0
bspc rule -a ffplay state=floating center=on rectangle=870x500+0+0
bspc rule -a Thunar state=floating center=on rectangle=870x500+0+0
bspc rule -a discord state=floating center=on rectangle=1200x700+0+0
bspc rule -a Mousepad state=floating center=on rectangle=830x730+0+0
bspc rule -a obsidian state=floating center=on rectangle=1050x700+0+0
bspc rule -a Nvidia-settings state=floating center=on rectangle=830x830+0+0
#bspc rule -a zathura state=floating center=on
#bspc rule -a File-roller state=floating center=on
bspc rule -a '*:*:Picture-in-Picture' state=floating
#bspc rule -a * floating=on

bspc config focused_border_color '#4c4c4c'
#bspc config normal_border_color '#323232'
#bspc config presel_feedback_color

xsetroot -cursor_name left_ptr
synclient TapButton1=1
