shadow = true;
shadow-radius = 11;
shadow-opacity = 0.31;
shadow-offset-x = -14;
shadow-offset-y = -10;
#shadow-color = "#000000"
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'firefox' && argb",
  "class_g = 'Firefox' && argb",
  "class_g = 'TelegramDesktop' && argb"
];

fading = true;
fade-in-step = 0.094;
fade-out-step = 0.094;
fade-delta = 10

#inactive-opacity = 0.80;
#frame-opacity = 0.9;
#inactive-opacity-override = false;
# active-opacity = 1.0
inactive-dim = 0.07

corner-radius = 8
rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'dmenu' && x = 0 && y = 0"
];

blur-method = "dual_kawase"
blur-size = 12
# blur-deviation = false
blur-strength = 19
blur-background = true
# blur-background-frame = false
blur-kern = "3x3box";
blur-background-exclude = [
#  "window_type = 'dock'",
  "window_type = 'desktop'",
  "class_g = 'firefox' && argb",
  "class_g = 'Firefox' && argb",
  "class_g = 'TelegramDesktop' && argb"
];

backend = "glx";
vsync = true;
dbe = true; 
# dbus = false
mark-wmwin-focused = true;
mark-ovredir-focused = true;
#detect-rounded-corners = false;
#detect-client-opacity = false;
# use-ewmh-active-win = false
detect-transient = true;
# resize-damage = 1
glx-no-stencil = true;
# glx-no-rebind-pixmap = false
use-damage = true;
log-level = "warn";

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.95; focus = true; full-shadow = false; };
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 1; }
  dropdown_menu = { opacity = 1; }
};
